(()=>{
 const $=id=>document.getElementById(id);let deferredInstall=null;let onboardingStep=0;let onboardingDraft={};
 const screens=[...document.querySelectorAll('.screen')];const navButtons=[...document.querySelectorAll('.bottom-nav button')];
 function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
 function go(view){screens.forEach(s=>s.classList.toggle('active',s.id===view));navButtons.forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='assistant')renderAssistant();if(view==='details')renderDetails()}
 navButtons.forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));

 function daysSince(date){if(!date)return Infinity;return Math.floor((Date.now()-new Date(date).getTime())/86400000)}
 function maintenanceDue(item){return daysSince(item.lastDone)>=item.intervalDays}
 function formatRelativeTask(item){if(!item.lastDone)return 'Ainda não realizada';const elapsed=daysSince(item.lastDone);const remaining=item.intervalDays-elapsed;if(remaining<=0)return 'Tarefa semanal pendente';if(remaining===1)return 'Novamente amanhã';return `Novamente dentro de ${remaining} dias`}
 function renderMaintenance(){const st=PoolStore.get(),list=$('maintenanceList');if(!list)return;list.innerHTML=st.maintenance.map(item=>`<div class="maintenance-item ${maintenanceDue(item)?'due':''}"><div><strong>${item.title}</strong><small>${formatRelativeTask(item)}</small></div><button class="maintenance-done" data-maintenance="${item.id}">${maintenanceDue(item)?'Concluir':'Feito novamente'}</button></div>`).join('');document.querySelectorAll('[data-maintenance]').forEach(btn=>btn.onclick=()=>{PoolStore.update(state=>{const task=state.maintenance.find(x=>x.id===btn.dataset.maintenance);if(task)task.lastDone=new Date().toISOString()});renderAll();toast('Manutenção registada.')})}
 function renderWeather(){const w=PoolStore.get().weather;if(!$('weatherTemperature'))return;if(w.temperature===null||w.temperature===undefined){$('weatherTemperature').textContent='Localização por definir';$('weatherDetail').textContent='Autorize a localização para obter a temperatura atual e ajustar a recomendação de filtração.';return}$('weatherTemperature').textContent=`${Number(w.temperature).toFixed(1).replace('.',',')} °C`;
  const updated=w.updatedAt?new Date(w.updatedAt).toLocaleString('pt-PT'):'agora';const threshold=PoolStore.get().pool.highTempThreshold;const advice=w.temperature>=threshold?`Temperatura elevada. Considere aumentar o tempo de filtração. Atualizado em ${updated}.`:`Temperatura abaixo do limite de maior filtração (${threshold} °C). Atualizado em ${updated}.`;$('weatherDetail').textContent=advice}
 async function updateWeather(){if(!navigator.geolocation)return toast('Este dispositivo não suporta localização.');$('updateWeatherBtn').textContent='A obter...';navigator.geolocation.getCurrentPosition(async pos=>{try{const {latitude,longitude}=pos.coords;const url=`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m&timezone=auto`;const response=await fetch(url);if(!response.ok)throw new Error('weather');const data=await response.json();PoolStore.update(st=>{st.weather={latitude,longitude,temperature:data.current.temperature_2m,updatedAt:new Date().toISOString()}});renderWeather();toast('Temperatura atualizada.')}catch(e){toast('Não foi possível obter a temperatura.')}finally{$('updateWeatherBtn').textContent='Atualizar'}},()=>{$('updateWeatherBtn').textContent='Atualizar';toast('A localização não foi autorizada.')},{enableHighAccuracy:false,timeout:10000,maximumAge:1800000})}
 async function enableNotifications(){if(!('Notification'in window))return toast('As notificações não são suportadas neste dispositivo.');const permission=await Notification.requestPermission();if(permission!=='granted')return toast('As notificações não foram autorizadas.');PoolStore.update(st=>st.notificationsEnabled=true);$('notificationBtn').textContent='Lembrete ativo';toast('Lembrete semanal ativado.');checkMaintenanceNotification(true)}
 async function checkMaintenanceNotification(force=false){const st=PoolStore.get();if(!st.notificationsEnabled||Notification.permission!=='granted')return;const due=st.maintenance.filter(maintenanceDue);if(!due.length)return;const notifiedRecently=st.lastMaintenanceNotification&&daysSince(st.lastMaintenanceNotification)<1;if(notifiedRecently&&!force)return;const title='Manutenção semanal da piscina';const body=due.length===1?due[0].title:`Tem ${due.length} tarefas de manutenção pendentes.`;try{const reg=await navigator.serviceWorker?.ready;if(reg)await reg.showNotification(title,{body,icon:'',tag:'poolcheck-maintenance'});else new Notification(title,{body})}catch(e){new Notification(title,{body})}PoolStore.update(x=>x.lastMaintenanceNotification=new Date().toISOString())}

 function latest(){return PoolStore.get().analyses[0]||null}
 function resultFor(a){return a?PoolChemistry.analyse(a,PoolStore.get().pool):null}
 function actionHTML(items){if(!items.length)return '<div class="action-item"><span class="action-number">✓</span><div><strong>Nenhuma ação necessária</strong><p>Volte a analisar dentro de 7 dias ou após chuva intensa, utilização elevada ou alteração visível da água.</p></div></div>';return items.map((i,n)=>`<div class="action-item"><span class="action-number">${n+1}</span><div><strong>${i.title}</strong><p>${i.reason}</p></div></div>`).join('')}
 function renderToday(){const a=latest(),r=resultFor(a),plan=PoolStore.get().activePlan,card=$('statusCard');card.className='status-card '+(r?.status||'neutral');$('todayTitle').textContent=r?.label||'Sem análise';$('statusMessage').textContent=r?.message||'Faça a primeira análise para saber se a piscina está pronta.';$('todayActions').innerHTML=actionHTML(r?.issues||[]);$('urgentBadge').classList.toggle('hidden',!r?.allIssues.some(i=>i.severity===3));
  const btn=$('primaryAction');if(plan&&!plan.completed){btn.textContent='Continuar tratamento';btn.onclick=()=>go('assistant')}else if(!a){btn.textContent='Analisar água';btn.onclick=()=>go('analysis')}else{btn.textContent='Fazer nova análise';btn.onclick=()=>go('analysis')}
  if(plan&&!plan.completed){$('nextTask').textContent=`Passo ${plan.current+1} de ${plan.steps.length}`;$('nextTaskDetail').textContent=plan.steps[plan.current]?.title||'Continuar plano.'}else if(a){$('nextTask').textContent='Nova análise dentro de 7 dias';$('nextTaskDetail').textContent=`Última análise: ${new Date(a.date).toLocaleDateString('pt-PT')}.`}else{$('nextTask').textContent='Primeira análise';$('nextTaskDetail').textContent='Ainda não existe uma análise registada.'}}
 function renderAssistant(){const plan=PoolStore.get().activePlan,box=$('planCard');if(!plan){$('assistantIntro').textContent='Faça uma análise para criar um plano.';box.innerHTML='<div class="action-item"><span class="action-number">1</span><div><strong>Comece pela análise da água</strong><p>O PoolCheck criará a ordem correta das ações.</p></div></div><button class="primary full" id="assistantAnalyse">Analisar água</button>';$('assistantAnalyse').onclick=()=>go('analysis');return}
  if(plan.completed||plan.current>=plan.steps.length){$('assistantIntro').textContent='Tratamento concluído.';box.innerHTML='<div class="plan-step"><p class="eyebrow">Concluído</p><h2>Piscina pronta</h2><p>O plano foi concluído. Faça uma nova análise na data indicada para confirmar os resultados.</p><button class="primary full" id="finishPlan">Voltar ao estado</button></div>';$('finishPlan').onclick=()=>{PoolStore.update(s=>{s.lastCompletedPlan=s.activePlan;s.activePlan=null});renderAll();go('today')};return}
  const s=plan.steps[plan.current],pct=Math.round((plan.current/plan.steps.length)*100);$('assistantIntro').textContent='Siga apenas esta instrução. O passo seguinte aparecerá depois.';box.innerHTML=`<div class="plan-step"><div class="plan-progress"><strong>Passo ${plan.current+1} de ${plan.steps.length}</strong><span>${pct}%</span></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><p class="eyebrow">${s.reason}</p><h2>${s.title}</h2><div class="instruction">${s.instruction}</div>${s.noSwim?'<p class="muted"><strong>Não utilize a piscina durante este período.</strong></p>':''}${s.waitHours?`<p class="muted">Depois de aplicar, aguarde aproximadamente ${s.waitHours} horas.</p>`:''}<div class="button-stack"><button class="primary full" id="completeStep">Concluído</button>${s.retest?'<button class="secondary full" id="retestNow">Fazer nova medição</button>':''}</div></div>`;
  $('completeStep').onclick=()=>{PoolStore.update(st=>{st.activePlan.steps[st.activePlan.current].done=true;st.activePlan.current++;if(st.activePlan.current>=st.activePlan.steps.length)st.activePlan.completed=true});renderAll();renderAssistant()};if($('retestNow'))$('retestNow').onclick=()=>go('analysis')}
 function renderDetails(){const st=PoolStore.get(),p=st.pool;$('poolSummary').innerHTML=[['Nome',p.name],['Tipo',label(p.type)],['Volume',`${p.volume} m³`],['Tratamento',label(p.treatment)],['Maior filtração',`A partir de ${p.highTempThreshold} °C`],['Cobertura',p.hasCover?'Sim':'Não']].map(x=>`<div class="summary-item"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');const a=latest();$('technicalValues').innerHTML=a?[['pH',a.ph],['Cloro livre',`${a.freeChlorine} ppm`],['Alcalinidade',`${a.alkalinity} ppm`],['Temperatura',a.waterTemp?`${a.waterTemp} °C`:'Não registada'],['Cloro total',a.totalChlorine??'Não registado'],['Estabilizador',a.cya??'Não registado']].map(x=>`<div class="technical-item"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join(''):'<p class="muted">Ainda não existem valores.</p>';
  $('historyList').innerHTML=st.analyses.length?st.analyses.slice(0,10).map(a=>{const r=resultFor(a);return`<div class="history-item"><strong>${r.label}</strong><small>${new Date(a.date).toLocaleString('pt-PT')}</small></div>`}).join(''):'<p class="muted">Ainda não existe histórico.</p>'}
 function label(v){return({enterrada:'Enterrada',elevada:'Elevada',spa:'Spa',cloro:'Cloro',sal:'Sal',bromo:'Bromo'})[v]||v}
 function renderAll(){renderToday();renderDetails();renderWeather();renderMaintenance();if($('notificationBtn'))$('notificationBtn').textContent=PoolStore.get().notificationsEnabled?'Lembrete ativo':'Ativar lembrete'}
 function openAnalysis(photo){$('analysisFormCard').classList.remove('hidden');$('photoField').classList.toggle('hidden',!photo);$('analysisFormCard').scrollIntoView({behavior:'smooth'})}
 $('updateWeatherBtn').onclick=updateWeather;$('notificationBtn').onclick=enableNotifications;
 $('photoAnalysisBtn').onclick=()=>openAnalysis(true);$('manualAnalysisBtn').onclick=()=>openAnalysis(false);$('closeAnalysisForm').onclick=()=> $('analysisFormCard').classList.add('hidden');
 $('analysisForm').onsubmit=e=>{e.preventDefault();const a={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(),date:new Date().toISOString(),ph:Number($('ph').value),freeChlorine:Number($('freeChlorine').value),alkalinity:Number($('alkalinity').value),waterTemp:$('waterTemp').value?Number($('waterTemp').value):null,totalChlorine:$('totalChlorine').value?Number($('totalChlorine').value):null,cya:$('cya').value?Number($('cya').value):null,hardness:$('hardness').value?Number($('hardness').value):null,notes:$('analysisNotes').value};const r=PoolChemistry.analyse(a,PoolStore.get().pool);PoolStore.update(s=>{s.analyses.unshift(a);s.activePlan=PoolChemistry.planFrom(r)});e.target.reset();$('analysisFormCard').classList.add('hidden');renderAll();toast('Análise guardada e plano criado.');go('assistant')};
 $('editPoolBtn').onclick=()=>{const p=PoolStore.get().pool;$('poolForm').classList.toggle('hidden');$('poolName').value=p.name;$('poolType').value=p.type;$('poolVolume').value=p.volume;$('treatmentType').value=p.treatment;$('highTempThreshold').value=p.highTempThreshold;$('hasCover').value=String(p.hasCover)};
 $('poolForm').onsubmit=e=>{e.preventDefault();PoolStore.update(s=>s.pool={name:$('poolName').value,type:$('poolType').value,volume:Number($('poolVolume').value),treatment:$('treatmentType').value,highTempThreshold:Number($('highTempThreshold').value)||28,hasCover:$('hasCover').value==='true'});$('poolForm').classList.add('hidden');renderAll();toast('Perfil atualizado.')};
 $('toggleTechnical').onclick=()=>{const el=$('technicalValues');el.classList.toggle('hidden');$('toggleTechnical').textContent=el.classList.contains('hidden')?'Mostrar':'Ocultar'};
 $('exportBtn').onclick=()=>{const blob=new Blob([PoolStore.export()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='poolcheck-v3-dados.json';a.click();URL.revokeObjectURL(a.href)};
 $('importFile').onchange=async e=>{try{PoolStore.replace(JSON.parse(await e.target.files[0].text()));renderAll();toast('Dados importados.')}catch(err){toast('Não foi possível importar o ficheiro.')}};
 $('resetBtn').onclick=()=>{if(confirm('Apagar todos os dados e reiniciar a aplicação?')){PoolStore.reset();location.reload()}};
 const steps=[
  {title:'Bem-vindo ao PoolCheck',text:'Vamos configurar a sua piscina. Demora cerca de 2 minutos.',type:'intro'},
  {title:'Que piscina tem?',key:'type',options:[['enterrada','Enterrada'],['elevada','Elevada'],['spa','Spa']]},
  {title:'Qual é o volume?',key:'volume',input:'number',placeholder:'36',suffix:'m³'},
  {title:'Como trata a água?',key:'treatment',options:[['cloro','Cloro'],['sal','Sal'],['bromo','Bromo']]},
  {title:'Tudo pronto',text:'Agora faça a primeira análise para saber se a piscina está pronta.',type:'finish'}];
 function renderOnboarding(){const step=steps[onboardingStep];$('onboardingProgress').textContent=`${onboardingStep+1} de ${steps.length}`;let body=`<div class="onboarding-panel"><p class="eyebrow">Configuração inicial</p><h1>${step.title}</h1>${step.text?`<p class="muted">${step.text}</p>`:''}`;if(step.options)body+=`<div class="option-list">${step.options.map(o=>`<button class="option-button ${onboardingDraft[step.key]===o[0]?'selected':''}" data-value="${o[0]}">${o[1]}</button>`).join('')}</div>`;if(step.input)body+=`<label>Volume da piscina<input id="onboardingInput" type="${step.input}" min="1" step="0.1" placeholder="${step.placeholder}" value="${onboardingDraft[step.key]||''}"></label>`;body+=`<div class="onboarding-actions">${onboardingStep?'<button id="onboardingBack" class="secondary">Anterior</button>':'<span></span>'}<button id="onboardingNext" class="primary">${step.type==='finish'?'Começar análise':'Continuar'}</button></div></div>`;$('onboardingContent').innerHTML=body;document.querySelectorAll('.option-button').forEach(b=>b.onclick=()=>{onboardingDraft[step.key]=b.dataset.value;renderOnboarding()});if($('onboardingBack'))$('onboardingBack').onclick=()=>{onboardingStep--;renderOnboarding()};$('onboardingNext').onclick=()=>{if(step.input){const v=Number($('onboardingInput').value);if(!v)return toast('Indique o volume da piscina.');onboardingDraft[step.key]=v}if(step.options&&!onboardingDraft[step.key])return toast('Selecione uma opção.');if(step.type==='finish'){PoolStore.update(s=>{s.onboardingComplete=true;s.pool={...s.pool,...onboardingDraft}});$('onboarding').classList.add('hidden');document.querySelector('.bottom-nav').classList.remove('hidden');renderAll();go('analysis')}else{onboardingStep++;renderOnboarding()}}}
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null;$('installBtn').classList.add('hidden')}};
 if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
 if(PoolStore.get().weather.latitude&&(!PoolStore.get().weather.updatedAt||daysSince(PoolStore.get().weather.updatedAt)>=1))updateWeather();checkMaintenanceNotification();
 if(!PoolStore.get().onboardingComplete){screens.forEach(s=>s.classList.remove('active'));$('onboarding').classList.remove('hidden');$('onboarding').classList.add('active');document.querySelector('.bottom-nav').classList.add('hidden');renderOnboarding()}else renderAll();
})();
