let deferredPrompt=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2600)}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function todayLocal(){const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
function num(id){const v=$("#"+id).value;return v===""?null:Number(v)}
function money(v){return Number(v||0).toLocaleString("pt-PT",{style:"currency",currency:"EUR"})}
function renderRecs(el,recs){el.innerHTML=recs.length?recs.map(r=>`<div class="recommendation ${r.severity}"><h4>${esc(r.title)}</h4><p>${esc(r.body)}</p>${r.action?`<p><strong>Ação:</strong> ${esc(r.action)}</p>`:""}</div>`).join(""):`<div class="empty-state">Sem recomendações.</div>`}
function latestAnalysis(){return PoolStore.get().analyses[0]}
function renderAll(){
  const s=PoolStore.get(),latest=latestAnalysis();
  $("#poolVolumeInput").value=s.profile.volume;$("#poolName").value=s.profile.name||"";$("#latitude").value=s.profile.latitude??"";$("#longitude").value=s.profile.longitude??"";
  if(latest){
    const ev=Chemistry.evaluate(latest,s.profile.volume);
    $("#overallStatus").textContent=ev.status;$("#statusDetail").textContent=`Última análise: ${new Date(latest.date).toLocaleString("pt-PT")}`;
    $("#dashPh").textContent=latest.ph;$("#dashChlorine").textContent=`${latest.freeChlorine} ppm`;$("#dashAlkalinity").textContent=`${latest.alkalinity} ppm`;$("#dashWaterTemp").textContent=latest.waterTemp!=null?`${latest.waterTemp} °C`:"—";
    const dot=$("#waterStatusDot");dot.className="status-dot "+(ev.status==="Equilibrada"?"ok":ev.status==="Atenção"?"warn":"bad");
    renderRecs($("#priorityRecommendations"),Chemistry.preventive(s).slice(0,5));
  }else renderRecs($("#priorityRecommendations"),Chemistry.preventive(s).slice(0,5));
  if(s.weather?.daily){
    const max=Math.max(...s.weather.daily.temperature_2m_max.slice(0,3)),rain=Math.max(...s.weather.daily.precipitation_sum.slice(0,3)),uv=Math.max(...s.weather.daily.uv_index_max.slice(0,3));
    $("#weatherHeadline").textContent=`Até ${Math.round(max)} °C`;$("#weatherDetail").textContent=rain>=10?`Chuva até ${Math.round(rain)} mm/dia`:"Sem chuva relevante";
    $("#weatherUv").textContent=uv.toFixed(1);$("#weatherRain").textContent=`${Math.round(rain)} mm`;
  }
  const proactive=Chemistry.preventive(s);$("#nextAction").textContent=proactive[0]?.title||"Sem ações urgentes";$("#nextActionDetail").textContent=proactive[0]?.body||"Mantém a rotina.";
  const hours=Chemistry.filtrationHours(s);$("#filtrationHours").textContent=hours;$("#filtrationReason").textContent=`Estimativa baseada na temperatura atual e no nível de utilização previsto.`;
  renderEquipment();renderEquipmentSummary();renderUpcoming();renderStock();renderCriticalStock();renderHistory();renderCosts();fillMaintenanceEquipment();fillStockUsageProducts();renderTrend();
  $("#weekendUsage").value=s.usage.weekend;$("#expectedPeople").value=s.usage.people;
  const g=s.github;$("#githubOwner").value=g.owner||"";$("#githubRepo").value=g.repo||"";$("#githubBranch").value=g.branch||"main";$("#githubToken").value=g.token||"";
  $("#githubStatus").textContent=s.lastSync?`Última sincronização: ${new Date(s.lastSync).toLocaleString("pt-PT")}`:"Ainda não sincronizado.";
  if(s.benchmarkImage)$("#benchmarkPreview").innerHTML=`<img src="${s.benchmarkImage}" alt="Tabela de referência">`;
}
function renderEquipment(){
  const s=PoolStore.get();
  $("#equipmentList").innerHTML=s.equipment.length?s.equipment.map(e=>`<div class="equipment-card"><h4>${esc(e.name)}</h4><p>${esc(e.type)}</p><div class="meta">Estado: ${e.status==="ok"?"OK":e.status==="attention"?"Atenção":"Avaria"}</div><div class="meta">${esc([e.brand,e.model].filter(Boolean).join(" · ")||"Sem marca/modelo")}</div><div class="meta">Próxima manutenção: ${esc(e.nextMaintenance||"não definida")}</div><div class="actions"><button class="secondary" onclick="cycleEquipmentStatus('${e.id}')">Alterar estado</button><button class="danger" onclick="deleteEquipment('${e.id}')">Eliminar</button></div></div>`).join(""):`<div class="empty-state">Adiciona os equipamentos.</div>`;
}
function renderEquipmentSummary(){const e=PoolStore.get().equipment;const counts={ok:e.filter(x=>x.status==="ok").length,attention:e.filter(x=>x.status==="attention").length,fault:e.filter(x=>x.status==="fault").length};$("#equipmentSummary").innerHTML=`<div class="equipment-summary-row"><span>Operacionais</span><strong>${counts.ok}</strong></div><div class="equipment-summary-row"><span>Atenção</span><strong>${counts.attention}</strong></div><div class="equipment-summary-row"><span>Avarias</span><strong>${counts.fault}</strong></div>`}
window.cycleEquipmentStatus=id=>{PoolStore.update(s=>{const e=s.equipment.find(x=>x.id===id);if(e)e.status=e.status==="ok"?"attention":e.status==="attention"?"fault":"ok"});renderAll()}
window.deleteEquipment=id=>{if(confirm("Eliminar este equipamento?")){PoolStore.update(s=>s.equipment=s.equipment.filter(e=>e.id!==id));renderAll()}};
function renderUpcoming(){const list=PoolStore.get().equipment.filter(e=>e.nextMaintenance).sort((a,b)=>a.nextMaintenance.localeCompare(b.nextMaintenance)).slice(0,6);$("#upcomingMaintenance").innerHTML=list.length?list.map(e=>`<div class="maintenance-item"><strong>${esc(e.name)}</strong><div>${esc(e.type)} · ${esc(e.nextMaintenance)}</div></div>`).join(""):`<div class="empty-state">Sem manutenções agendadas.</div>`}
function renderStock(){const s=PoolStore.get();$("#stockList").innerHTML=s.stock.length?s.stock.map(x=>{const pct=Math.max(0,Math.min(100,Math.round((Number(x.qty)/(Number(x.min)||1))*50)));return `<div class="stock-card ${Number(x.qty)<=Number(x.min)?"critical":""}"><h4>${esc(x.name)}</h4><p>${x.qty} ${esc(x.unit)} disponíveis</p><div class="stock-bar"><span style="width:${pct}%"></span></div><div class="meta">Mínimo: ${x.min} ${esc(x.unit)}</div><div class="actions"><button class="danger" onclick="deleteStock('${x.id}')">Eliminar</button></div></div>`}).join(""):`<div class="empty-state">Sem produtos registados.</div>`}
function renderCriticalStock(){const x=PoolStore.get().stock.filter(x=>Number(x.qty)<=Number(x.min));$("#criticalStock").innerHTML=x.length?x.map(i=>`<div class="maintenance-item"><strong>${esc(i.name)}</strong><div>${i.qty} ${esc(i.unit)} disponíveis</div></div>`).join(""):`<div class="empty-state">Sem stock crítico.</div>`}
window.deleteStock=id=>{if(confirm("Eliminar este produto?")){PoolStore.update(s=>s.stock=s.stock.filter(x=>x.id!==id));renderAll()}};
function fillMaintenanceEquipment(){const sel=$("#maintenanceEquipment"),cur=sel.value;sel.innerHTML=PoolStore.get().equipment.map(e=>`<option value="${e.id}">${esc(e.name)} · ${esc(e.type)}</option>`).join("");if(cur)sel.value=cur}
function fillStockUsageProducts(){const sel=$("#stockUsageProduct"),cur=sel.value;sel.innerHTML=PoolStore.get().stock.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("");if(cur)sel.value=cur}
function renderHistory(){const s=PoolStore.get();$("#historyList").innerHTML=s.analyses.length?s.analyses.map(a=>`<div class="history-item"><strong>${new Date(a.date).toLocaleString("pt-PT")}</strong><div>pH ${a.ph} · Cloro ${a.freeChlorine} ppm · Alcalinidade ${a.alkalinity} ppm</div>${a.notes?`<div>${esc(a.notes)}</div>`:""}</div>`).join(""):`<div class="empty-state">Sem análises.</div>`;$("#maintenanceHistory").innerHTML=s.maintenance.length?s.maintenance.map(m=>{const e=s.equipment.find(x=>x.id===m.equipmentId);return `<div class="history-item"><strong>${esc(e?.name||"Equipamento removido")} · ${esc(m.date)}</strong><div>${esc(m.type)} · ${esc(m.description)}</div>${m.cost?`<div>Custo: ${money(m.cost)}</div>`:""}</div>`}).join(""):`<div class="empty-state">Sem registos.</div>`}
function renderCosts(){const s=PoolStore.get(),year=new Date().getFullYear();const total=s.costs.reduce((a,c)=>a+Number(c.amount||0),0)+s.maintenance.reduce((a,m)=>a+Number(m.cost||0),0);const yr=s.costs.filter(c=>new Date(c.date).getFullYear()===year).reduce((a,c)=>a+Number(c.amount||0),0)+s.maintenance.filter(m=>new Date(m.date).getFullYear()===year).reduce((a,m)=>a+Number(m.cost||0),0);const maint=s.maintenance.reduce((a,m)=>a+Number(m.cost||0),0)+s.costs.filter(c=>c.category==="maintenance").reduce((a,c)=>a+Number(c.amount||0),0);const products=s.costs.filter(c=>c.category==="products").reduce((a,c)=>a+Number(c.amount||0),0);$("#costYear").textContent=money(yr);$("#costMaintenance").textContent=money(maint);$("#costProducts").textContent=money(products);$("#costTotal").textContent=money(total);$("#costHistory").innerHTML=s.costs.length?s.costs.map(c=>`<div class="history-item"><strong>${esc(c.description)}</strong><div>${esc(c.date)} · ${esc(c.category)} · ${money(c.amount)}</div></div>`).join(""):`<div class="empty-state">Sem despesas.</div>`}
function renderTrend(){const c=$("#trendChart"),ctx=c.getContext("2d"),d=PoolStore.get().analyses.slice(0,10).reverse();const w=c.width=c.clientWidth*devicePixelRatio,h=c.height=130*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);ctx.clearRect(0,0,c.clientWidth,130);if(d.length<2){ctx.fillStyle="#647784";ctx.font="14px sans-serif";ctx.fillText("São necessárias pelo menos duas análises.",16,30);return}const width=c.clientWidth,pad=28,plotW=width-pad*2,plotH=80;ctx.strokeStyle="#d7e3ea";ctx.lineWidth=1;for(let i=0;i<4;i++){const y=20+i*(plotH/3);ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(width-pad,y);ctx.stroke()}function line(vals,min,max,offset){ctx.beginPath();vals.forEach((v,i)=>{const x=pad+i*(plotW/(vals.length-1)),y=20+plotH-(v-min)/(max-min)*plotH+(offset||0);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.lineWidth=2;ctx.stroke()}ctx.strokeStyle="#0b6ea8";line(d.map(x=>x.ph),6.8,8.2);ctx.strokeStyle="#1b8f55";line(d.map(x=>x.freeChlorine),0,5)}
async function refreshWeather(){const s=PoolStore.get();if(s.profile.latitude==null||s.profile.longitude==null)return;try{const w=await WeatherService.fetchForecast(s.profile.latitude,s.profile.longitude);PoolStore.update(x=>x.weather=w);renderAll()}catch(e){toast(e.message)}}
function fileToData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
$$(".tabs button").forEach(b=>b.onclick=()=>{$$(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".view").forEach(v=>v.classList.remove("active"));$("#"+b.dataset.view).classList.add("active")});
$("#analysisDate").value=todayLocal();$("#maintenanceDate").value=$("#stockUsageDate").value=$("#costDate").value=new Date().toISOString().slice(0,10);
$("#analysisForm").onsubmit=async e=>{e.preventDefault();let photo=null;const f=$("#stripPhoto").files[0];if(f)photo=await fileToData(f);const a={id:crypto.randomUUID(),date:$("#analysisDate").value,waterTemp:num("waterTemp"),ph:num("ph"),freeChlorine:num("freeChlorine"),totalChlorine:num("totalChlorine"),alkalinity:num("alkalinity"),cya:num("cya"),hardness:num("hardness"),notes:$("#analysisNotes").value,photo};renderRecs($("#analysisResult"),Chemistry.evaluate(a,PoolStore.get().profile.volume).recs);PoolStore.update(s=>s.analyses.unshift(a));renderAll();toast("Análise guardada.")};
$("#saveBenchmark").onclick=async()=>{const f=$("#benchmarkPhoto").files[0];if(!f)return toast("Seleciona uma imagem.");const img=await fileToData(f);PoolStore.update(s=>s.benchmarkImage=img);renderAll();toast("Referência guardada.")};
$("#runAssistant").onclick=$("#runQuickAssistant").onclick=()=>renderRecs($("#assistantOutput"),Chemistry.preventive(PoolStore.get()));
$("#refreshRecommendations").onclick=()=>renderRecs($("#priorityRecommendations"),Chemistry.preventive(PoolStore.get()).slice(0,5));
$("#saveUsage").onclick=()=>{PoolStore.update(s=>s.usage={weekend:$("#weekendUsage").value,people:Number($("#expectedPeople").value||0)});renderAll();toast("Previsão guardada.")};
$("#addEquipmentBtn").onclick=()=>$("#equipmentDialog").showModal();
$("#equipmentForm").onsubmit=e=>{if(e.submitter?.value==="cancel")return;const item={id:crypto.randomUUID(),type:$("#equipmentType").value,name:$("#equipmentName").value,status:$("#equipmentStatus").value,brand:$("#equipmentBrand").value,model:$("#equipmentModel").value,installDate:$("#equipmentInstallDate").value,nextMaintenance:$("#equipmentNextMaintenance").value,notes:$("#equipmentNotes").value};PoolStore.update(s=>s.equipment.push(item));setTimeout(()=>{renderAll();toast("Equipamento adicionado.");$("#equipmentForm").reset()},0)};
$("#maintenanceForm").onsubmit=e=>{e.preventDefault();const item={id:crypto.randomUUID(),equipmentId:$("#maintenanceEquipment").value,type:$("#maintenanceType").value,date:$("#maintenanceDate").value,cost:num("maintenanceCost"),description:$("#maintenanceDescription").value,nextDate:$("#maintenanceNextDate").value};PoolStore.update(s=>{s.maintenance.unshift(item);if(item.nextDate){const eq=s.equipment.find(x=>x.id===item.equipmentId);if(eq)eq.nextMaintenance=item.nextDate}});e.target.reset();$("#maintenanceDate").value=new Date().toISOString().slice(0,10);renderAll();toast("Registo guardado.")};
$("#addStockBtn").onclick=()=>$("#stockDialog").showModal();
$("#stockForm").onsubmit=e=>{if(e.submitter?.value==="cancel")return;PoolStore.update(s=>s.stock.push({id:crypto.randomUUID(),name:$("#stockName").value,unit:$("#stockUnit").value,qty:num("stockQty"),min:num("stockMin"),cost:num("stockCost")}));setTimeout(()=>{renderAll();toast("Produto adicionado.");$("#stockForm").reset()},0)};
$("#stockUsageForm").onsubmit=e=>{e.preventDefault();const id=$("#stockUsageProduct").value,qty=num("stockUsageQty");PoolStore.update(s=>{const p=s.stock.find(x=>x.id===id);if(p)p.qty=Math.max(0,Number(p.qty)-qty);s.stockUsage.unshift({id:crypto.randomUUID(),productId:id,qty,date:$("#stockUsageDate").value,reason:$("#stockUsageReason").value})});e.target.reset();$("#stockUsageDate").value=new Date().toISOString().slice(0,10);renderAll();toast("Consumo registado.")};
$("#costForm").onsubmit=e=>{e.preventDefault();PoolStore.update(s=>s.costs.unshift({id:crypto.randomUUID(),category:$("#costCategory").value,amount:num("costAmount"),date:$("#costDate").value,description:$("#costDescription").value}));e.target.reset();$("#costDate").value=new Date().toISOString().slice(0,10);renderAll();toast("Despesa guardada.")};
$("#poolSettingsForm").onsubmit=e=>{e.preventDefault();PoolStore.update(s=>s.profile={name:$("#poolName").value,volume:Number($("#poolVolumeInput").value),latitude:num("latitude"),longitude:num("longitude")});renderAll();refreshWeather();toast("Perfil guardado.")};
$("#useLocation").onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{$("#latitude").value=p.coords.latitude;$("#longitude").value=p.coords.longitude;toast("Localização obtida.")},()=>toast("Não foi possível obter a localização.")):toast("Geolocalização indisponível.");
function saveGithubForm(){PoolStore.update(s=>s.github={owner:$("#githubOwner").value.trim(),repo:$("#githubRepo").value.trim(),branch:$("#githubBranch").value.trim()||"main",token:$("#githubToken").value.trim()})}
$("#githubForm").onsubmit=e=>{e.preventDefault();saveGithubForm();renderAll();toast("Configuração GitHub guardada.")};
$("#testGithub").onclick=async()=>{saveGithubForm();$("#githubStatus").textContent="A testar...";try{const r=await GitHubSync.test();$("#githubStatus").textContent=`Ligação válida: ${r.full_name}`;toast("Ligação válida.")}catch(e){$("#githubStatus").textContent=e.message}};
$("#syncNow").onclick=async()=>{saveGithubForm();$("#githubStatus").textContent="A sincronizar...";try{await GitHubSync.pushAll();renderAll();toast("Dados sincronizados.")}catch(e){$("#githubStatus").textContent=e.message}};
$("#exportData").onclick=()=>{const blob=new Blob([PoolStore.exportData()],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`poolcheck-v2-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$("#importData").onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());const token=PoolStore.get().github.token;PoolStore.replace(data);PoolStore.update(s=>s.github.token=token);renderAll();toast("Dados importados.")}catch{toast("Ficheiro inválido.")}};
$("#clearLocalData").onclick=()=>{if(confirm("Apagar todos os dados locais?")){PoolStore.clear();renderAll();toast("Dados apagados.")}};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").classList.remove("hidden")});
$("#installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("#installBtn").classList.add("hidden")}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
renderAll();refreshWeather();