const PoolIntelligence=(()=>{
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
 const hours=(a,b)=>(new Date(b)-new Date(a))/36e5;
 function models(state){
  const analyses=[...(state.analyses||[])].sort((a,b)=>new Date(a.date)-new Date(b.date));
  const products=state.productHistory||[];
  const result={chlorineDecay:null,phTrend:null,alkTrend:null,confidence:'Baixa',samples:0};
  const diffs=[];
  for(let i=1;i<analyses.length;i++){const prev=analyses[i-1],cur=analyses[i],h=hours(prev.date,cur.date);if(h>=6&&h<=240&&Number.isFinite(prev.freeChlorine)&&Number.isFinite(cur.freeChlorine)){const additions=products.some(p=>new Date(p.date)>new Date(prev.date)&&new Date(p.date)<new Date(cur.date)&&['fastChlorine','liquidChlorine','multitabs','slowChlorine'].includes(p.productId));if(!additions)diffs.push((prev.freeChlorine-cur.freeChlorine)/(h/24));}}
  if(diffs.length){result.chlorineDecay=clamp(diffs.reduce((a,b)=>a+b,0)/diffs.length,0,3);result.samples=diffs.length;result.confidence=diffs.length>=5?'Alta':diffs.length>=3?'Média':'Baixa';}
  const trend=(key)=>{if(analyses.length<2)return null;const recent=analyses.slice(-5);const first=recent[0],last=recent.at(-1),d=Math.max(1,hours(first.date,last.date)/24);return (Number(last[key])-Number(first[key]))/d;};
  result.phTrend=trend('ph');result.alkTrend=trend('alkalinity');return result;
 }
 function predict(state){const latest=state.analyses?.[0];if(!latest)return[];const m=models(state);const temp=Number(latest.waterTemp||state.weather?.temperature||25);const heatFactor=temp>30?1.25:temp>27?1.1:1;const covered=state.pool?.coverType&&state.pool.coverType!=='none'&&state.pool.coverUsage!=='rarely';const coverFactor=covered?.8:1;const decay=(m.chlorineDecay??0.35)*heatFactor*coverFactor;const days=[1,3,5];const out=days.map(day=>({parameter:'Cloro livre',day,value:Math.max(0,latest.freeChlorine-decay*day),low:Math.max(0,latest.freeChlorine-decay*day*1.35),high:Math.max(0,latest.freeChlorine-decay*day*.65),confidence:m.confidence}));if(m.phTrend!==null)out.push({parameter:'pH',day:3,value:latest.ph+m.phTrend*3,low:latest.ph+m.phTrend*3-.15,high:latest.ph+m.phTrend*3+.15,confidence:m.confidence});return out;}
 function score(state,result){const a=state.analyses?.[0];if(!a)return{total:0,label:'Sem dados',dimensions:{chemistry:0,safety:0,maintenance:0,trend:0,environment:0,data:0},reasons:['Faça a primeira análise.']};
  const p=(v,min,max,soft=.3)=>v>=min&&v<=max?100:Math.max(0,100-Math.abs(v<(min)?min-v:v-max)/soft*25);
  const chemistry=Math.round((p(a.ph,7.2,7.6,.2)*.35+p(a.freeChlorine,1,4,1)*.35+p(a.alkalinity,80,140,20)*.3));
  let safety=100;const critical=(result?.allIssues||[]).filter(i=>i.severity===3);safety-=critical.length*30;if((result?.allIssues||[]).some(i=>i.blocked))safety-=15;safety=clamp(safety,0,100);
  const due=(state.maintenance||[]).filter(t=>t.enabled!==false&&(!t.lastDone||Date.now()-new Date(t.lastDone)>Number(t.intervalDays||7)*864e5)).length;const maintenance=clamp(100-due*18,0,100);
  const pred=predict(state);const danger=pred.some(x=>x.parameter==='Cloro livre'&&x.day<=3&&x.low<1);const trend=danger?45:pred.length?80:55;
  const w=state.weather?.impact?.level||0;const environment=clamp(100-w*15,40,100);const count=state.analyses?.length||0;const data=clamp(35+count*12,35,100);
  const weighted=Math.round(chemistry*.4+safety*.2+maintenance*.15+trend*.1+environment*.1+data*.05);let cap=100;if(a.freeChlorine<.5||a.ph<6.8||a.ph>8.2)cap=45;const total=Math.min(weighted,cap);return{total,label:total>=85?'Excelente':total>=70?'Boa':total>=50?'Requer atenção':'Crítica',dimensions:{chemistry,safety,maintenance,trend,environment,data},reasons:critical.map(x=>x.title).slice(0,3)};}
 function answer(question,state,result){const q=String(question||'').toLowerCase();const latest=state.analyses?.[0];if(!latest)return'Preciso de uma análise da água antes de interpretar o estado da piscina.';if(q.includes('pH')||q.includes('ph')){if(latest.alkalinity<80)return`O pH é ${latest.ph}, mas a alcalinidade está em ${latest.alkalinity} ppm. Corrija primeiro a alcalinidade e volte a medir antes de usar pH+ ou pH-.`;return`O pH atual é ${latest.ph}. O intervalo operacional definido é 7,2 a 7,6. Siga apenas a dose faseada calculada pelo motor químico.`;}if(q.includes('cloro')){const pred=predict(state).find(x=>x.parameter==='Cloro livre'&&x.day===3);return`O cloro livre atual é ${latest.freeChlorine} ppm.${pred?` Em três dias, a estimativa é ${pred.low.toFixed(1)} a ${pred.high.toFixed(1)} ppm, com confiança ${pred.confidence.toLowerCase()}.`:''} Confirme sempre com uma análise antes de dosear.`;}if(q.includes('segura')||q.includes('usar')||q.includes('nadar')){const unsafe=(result?.allIssues||[]).some(i=>i.noSwim);return unsafe?'Não considero a piscina pronta para utilização. Existem condições que exigem correção ou confirmação por nova análise.':'Os parâmetros registados não mostram um bloqueio explícito, mas confirme visualmente a água e siga o plano ativo.';}const first=result?.allIssues?.[0];return first?`A prioridade atual é: ${first.title}. ${first.reason} ${first.instruction}`:'A água está dentro dos intervalos definidos. Mantenha a rotina e volte a analisar após utilização intensa, chuva ou alteração visível.';}
 return{models,predict,score,answer};
})();
