(()=>{
const $=s=>document.querySelector(s); const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function ensure(){PoolStore.update(s=>{s.version=3;s.onboarding=s.onboarding||{completed:false,step:0};s.profile={shape:"rectangular",length:6,width:4,depthMin:1.2,depthMax:1.8,environment:"outdoor",treatment:"Cloro",filter:"Filtro de areia",liner:"",highTempThreshold:28,...s.profile};s.tablets=s.tablets||[];s.tasks=s.tasks||[];s.season=s.season||{opening:{},closing:{}};s.productsVersion=3});}
ensure();
const steps=[
{title:"Bem-vindo",html:()=>`<div class="empty-state"><h3>Configura a piscina em cerca de 5 minutos</h3><p>As dosagens, a filtração e os alertas serão personalizados.</p></div>`},
{title:"Perfil da piscina",html:s=>`<div class="form-grid"><label>Nome<input data-w="name" value="${esc(s.profile.name)}"></label><label>Forma<select data-w="shape"><option value="rectangular">Retangular</option><option value="oval">Oval</option><option value="round">Circular</option></select></label><label>Comprimento, m<input data-w="length" type="number" step=".1" value="${s.profile.length}"></label><label>Largura, m<input data-w="width" type="number" step=".1" value="${s.profile.width}"></label><label>Profundidade mínima<input data-w="depthMin" type="number" step=".1" value="${s.profile.depthMin}"></label><label>Profundidade máxima<input data-w="depthMax" type="number" step=".1" value="${s.profile.depthMax}"></label><label class="full">Volume calculado/real, m³<input data-w="volume" type="number" step=".1" value="${s.profile.volume}"></label></div>`},
{title:"Tratamento e filtro",html:s=>`<div class="form-grid"><label>Tratamento<select data-w="treatment"><option>Cloro</option><option>Sal</option><option>Bromo</option><option>Outro</option></select></label><label>Filtro<select data-w="filter"><option>Filtro de areia</option><option>Filtro de vidro</option><option>Filtro de cartucho</option><option>Outro</option></select></label><label>Localização<select data-w="environment"><option value="outdoor">Exterior</option><option value="indoor">Interior</option></select></label><label>Revestimento<input data-w="liner" value="${esc(s.profile.liner)}"></label></div>`},
{title:"Equipamentos",html:()=>`<div class="v3-choice-grid"><div class="v3-choice">Bomba de circulação</div><div class="v3-choice">Filtro</div><div class="v3-choice">Robot</div><div class="v3-choice">Bomba de calor</div></div><p class="muted">Podes completar marcas, modelos e garantias na área Equipamentos.</p>`},
{title:"Produtos",html:()=>`<p>O stock inicial já inclui pastilhas 5 ações, pH+, pH-, cloro rápido e alcalinidade.</p><p class="muted">Na V3 podes adicionar a marca, dosagem do rótulo e custo em Produtos.</p>`},
{title:"Tiras de análise",html:()=>`<p>Na área Análise fotografa a tabela do fabricante e a tira utilizada.</p><div class="status-box">A leitura visual é assistida e deve ser confirmada antes de guardar.</div>`},
{title:"Meteorologia e filtração",html:s=>`<div class="form-grid"><label class="full">Temperatura para reforçar filtração<select data-w="highTempThreshold"><option value="26">26 °C</option><option value="28">28 °C, recomendado</option><option value="30">30 °C</option><option value="32">32 °C</option></select></label></div><div class="status-box">Aos ${s.profile.highTempThreshold||28} °C, o PoolCheck aumenta a recomendação de filtração e reforça o controlo do cloro.</div>`},
{title:"Rotina",html:()=>`<div class="v3-choice-grid"><div class="v3-choice">Analisar água semanalmente</div><div class="v3-choice">Limpar skimmers semanalmente</div><div class="v3-choice">Verificar filtro mensalmente</div><div class="v3-choice">Inspecionar bomba mensalmente</div></div>`},
{title:"Sincronização",html:()=>`<p>Podes configurar GitHub agora na área Configuração ou continuar apenas com dados locais.</p>`},
{title:"Concluído",html:()=>`<div class="empty-state"><h3>Configuração concluída</h3><p>Faz a primeira análise para gerar o plano de tratamento.</p></div>`}
];
let step=PoolStore.get().onboarding.step||0;
function saveFields(){document.querySelectorAll('[data-w]').forEach(el=>{let v=el.type==='number'?Number(el.value):el.value;PoolStore.update(s=>s.profile[el.dataset.w]=v)});const p=PoolStore.get().profile;if(step===1&&p.shape==='rectangular'){const calc=p.length*p.width*((p.depthMin+p.depthMax)/2);if(calc>0&&Math.abs(calc-p.volume)>2&&!confirm(`O volume geométrico é ${calc.toFixed(1)} m³. Manter ${p.volume} m³?`))PoolStore.update(s=>s.profile.volume=Number(calc.toFixed(1)));}}
function renderWizard(){const s=PoolStore.get();$('#v3StepLabel').textContent=`Passo ${step+1} de ${steps.length}: ${steps[step].title}`;$('#v3ProgressBar').style.width=`${(step+1)/steps.length*100}%`;$('#v3WizardContent').innerHTML=steps[step].html(s);document.querySelectorAll('[data-w]').forEach(el=>{if(el.tagName==='SELECT'&&s.profile[el.dataset.w]!=null)el.value=s.profile[el.dataset.w]});$('#v3Back').disabled=step===0;$('#v3Next').textContent=step===steps.length-1?'Entrar no PoolCheck':'Continuar';}
function openWizard(force=false){step=force?0:(PoolStore.get().onboarding.step||0);$('#v3Wizard').classList.remove('hidden');renderWizard()}
$('#openV3Wizard').onclick=()=>openWizard(true);$('#v3WizardExit').onclick=()=>{saveFields();PoolStore.update(s=>s.onboarding.step=step);$('#v3Wizard').classList.add('hidden');renderV3()};$('#v3Back').onclick=()=>{saveFields();step=Math.max(0,step-1);renderWizard()};$('#v3Skip').onclick=()=>{step=Math.min(steps.length-1,step+1);renderWizard()};$('#v3Next').onclick=()=>{saveFields();if(step<steps.length-1){step++;PoolStore.update(s=>s.onboarding.step=step);renderWizard()}else{PoolStore.update(s=>s.onboarding={completed:true,step:0});$('#v3Wizard').classList.add('hidden');renderV3();toast('PoolCheck V3 configurado.')}};
const diag={green:["Algas ou desinfeção insuficiente","Medir pH e cloro","Corrigir pH primeiro","Aplicar cloro de choque conforme o rótulo","Escovar paredes e filtrar continuamente"],cloudy:["Filtração insuficiente, partículas ou água desequilibrada","Medir pH, cloro e alcalinidade","Limpar o filtro","Aumentar filtração","Usar floculante apenas conforme o rótulo"],odor:["Possível cloro combinado, não excesso de cloro livre","Comparar cloro total e livre","Ventilar e evitar utilização","Considerar choque se diferença superior a 0,5 ppm"],algae:["Foco localizado de algas","Escovar a zona","Verificar circulação","Corrigir pH e aplicar tratamento conforme rótulo"],foam:["Resíduos orgânicos ou excesso de produto","Não adicionar mais produto","Renovar parcialmente a água se persistir","Limpar linha de água e filtro"],loss:["UV, CYA baixo, calor ou carga orgânica","Medir CYA","Verificar doseador e pastilha","Aumentar filtração em dias quentes"],ph:["Alcalinidade fora do intervalo","Medir alcalinidade","Corrigir alcalinidade antes de perseguir o pH","Fazer alterações graduais"]};
$('#v3Diagnose').onclick=()=>{$('#v3Diagnosis').innerHTML=diag[$('#v3Symptom').value].map((x,i)=>`<div class="recommendation ${i===0?'high':'medium'}"><h4>${i===0?'Causa provável':`Passo ${i}`}</h4><p>${esc(x)}</p></div>`).join('')};
function addDays(d,n){const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}
$('#v3TabletDate').value=new Date().toISOString().slice(0,10);$('#v3TabletForm').onsubmit=e=>{e.preventDefault();PoolStore.update(s=>s.tablets.unshift({id:crypto.randomUUID(),date:$('#v3TabletDate').value,qty:Number($('#v3TabletQty').value),weight:Number($('#v3TabletWeight').value),days:Number($('#v3TabletDays').value),location:$('#v3TabletLocation').value}));renderV3();toast('Pastilha registada.')};
$('#v3TaskDate').value=new Date().toISOString().slice(0,10);$('#v3TaskForm').onsubmit=e=>{e.preventDefault();PoolStore.update(s=>s.tasks.push({id:crypto.randomUUID(),title:$('#v3TaskTitle').value,date:$('#v3TaskDate').value,frequency:$('#v3TaskFrequency').value,category:$('#v3TaskCategory').value,done:false}));e.target.reset();$('#v3TaskDate').value=new Date().toISOString().slice(0,10);renderV3()};
const opening=["Retirar e limpar a cobertura","Inspecionar bomba, filtro e tubagens","Repor o nível da água","Limpar fundo, paredes e skimmers","Fazer lavagem e enxaguamento do filtro","Analisar pH, cloro e alcalinidade","Corrigir a água por etapas","Executar choque se necessário","Filtrar e voltar a medir antes da utilização"];
const closing=["Limpar completamente a piscina","Equilibrar pH e alcalinidade","Aplicar produto de inverno conforme rótulo","Filtrar durante o período recomendado","Reduzir o nível apenas se necessário","Proteger tubagens e equipamentos","Limpar e guardar robot e acessórios","Instalar a cobertura","Registar a data de encerramento"];
function checklist(el,arr,key){el.innerHTML=arr.map((x,i)=>`<label class="v3-check"><input type="checkbox" data-season="${key}" data-index="${i}" ${PoolStore.get().season[key][i]?'checked':''}><span>${esc(x)}</span></label>`).join('');el.querySelectorAll('input').forEach(c=>c.onchange=()=>PoolStore.update(s=>s.season[c.dataset.season][c.dataset.index]=c.checked))}
function predictions(){const a=PoolStore.get().analyses.slice(0,6).reverse(),out=[];if(a.length>=3){const ph=(a[a.length-1].ph-a[0].ph)/(a.length-1);const cl=(a[a.length-1].freeChlorine-a[0].freeChlorine)/(a.length-1);out.push({severity:Math.abs(ph)>.1?'medium':'low',title:'Tendência do pH',body:`Variação média de ${ph>=0?'+':''}${ph.toFixed(2)} por análise.`});out.push({severity:cl<-.3?'medium':'low',title:'Tendência do cloro',body:`Variação média de ${cl>=0?'+':''}${cl.toFixed(2)} ppm por análise.`})}else out.push({severity:'low',title:'Dados insuficientes',body:'São necessárias pelo menos 3 análises para prever tendências.'});return out}
function renderV3(){const s=PoolStore.get(),t=s.tablets[0];$('#v3TabletCurrent').innerHTML=t?`<h3>${t.qty} pastilha(s) de ${t.weight} g</h3><p>${esc(t.location)} · colocada em ${t.date}</p><p><strong>Substituição estimada:</strong> ${addDays(t.date,t.days)}</p>`:'<div class="empty-state">Sem registos.</div>';$('#v3TabletHistory').innerHTML=s.tablets.length?s.tablets.map(x=>`<div class="history-item"><strong>${x.date}</strong><div>${x.qty} × ${x.weight} g · ${esc(x.location)} · ${x.days} dias</div></div>`).join(''):'<div class="empty-state">Sem histórico.</div>';$('#v3TaskList').innerHTML=s.tasks.length?s.tasks.sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<label class="v3-check"><input type="checkbox" ${x.done?'checked':''} data-task="${x.id}"><span><strong>${esc(x.title)}</strong><br><span class="muted">${x.date} · ${esc(x.frequency)} · ${esc(x.category)}</span></span></label>`).join(''):'<div class="empty-state">Sem tarefas.</div>';$('#v3TaskList').querySelectorAll('[data-task]').forEach(c=>c.onchange=()=>PoolStore.update(s=>{const t=s.tasks.find(x=>x.id===c.dataset.task);if(t)t.done=c.checked}));checklist($('#v3Opening'),opening,'opening');checklist($('#v3Closing'),closing,'closing');const p=s.profile;let card=document.querySelector('.pool-profile-summary');if(!card){card=document.createElement('article');card.className='card pool-profile-summary';document.querySelector('#dashboard').prepend(card)}card.innerHTML=`<div class="card-head"><div><span class="eyebrow">Piscina ativa</span><h2>${esc(p.name)}</h2><p class="muted">${p.length||'—'} × ${p.width||'—'} m · ${p.volume} m³ · ${p.environment==='outdoor'?'Exterior':'Interior'}</p></div><div><span class="status-pill pending">${esc(p.treatment)}</span> <span class="status-pill pending">Reforço aos ${p.highTempThreshold||28} °C</span></div></div>`;let pred=document.querySelector('#trendPredictionsV3');if(!pred){const a=document.createElement('article');a.className='card';a.innerHTML='<h3>Previsões de tendência</h3><div id="trendPredictionsV3" class="recommendation-list"></div>';document.querySelector('#dashboard .grid.two')?.appendChild(a);pred=$('#trendPredictionsV3')}if(pred)renderRecs(pred,predictions())}
if(!PoolStore.get().onboarding.completed)setTimeout(()=>openWizard(false),250);renderV3();
})();
